<h2>New Topic</h2>
<form action="/topic/add" method="POST">
    <div class="form-group">
        <label for="">Title:</label>
        <input type="text" name="title" class="form-control">
    </div>
    <div class="form-group">
        <label for="">Description:</label>
        <textarea name="description" rows="3" class="form-control"></textarea>
    </div>
    <input type="submit" class="btn btn-primary" value="Add Topic">
</form>