<?php
$topic = $this->topic;
?>
<h2>Edit Topic</h2>
<form action="/topic/edit" method="POST">
    <div class="form-group">
        <label for="">Title:</label>
        <input type="text" name="title" class="form-control" value="<?= $topic['title']; ?>">
    </div>
    <div class="form-group">
        <label for="">Description:</label>
        <textarea name="description" rows="3" class="form-control"><?= $topic['description']; ?></textarea>
    </div>
    <input type="hidden" name="id" value="<?= $topic['id']; ?>">
    <input type="submit" class="btn btn-primary" value="Edit Topic">
</form>